version: '3.8'
services:
  app1:
    container_name: app1
    build:
      context: .
    ports:
      - '3001:3000'
    environment:
      - APP_NAME=App1

  app2:
    container_name: app2
    build:
      context: .
    ports:
      - '3002:3000'
    environment:
      - APP_NAME=App2

  app3:
    container_name: app3
    build:
      context: .
    ports:
      - '3003:3000'
    environment:
      - APP_NAME=App3

  app4:
    container_name: app4
    build:
      context: .
    ports:
      - '3004:3000'
    environment:
      - APP_NAME=App4

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx # 로그 디렉토리 공유
    ports:
      - '8080:80'
    depends_on:
      - app1
      - app2
      - app3
      - app4

  elasticsearch:
    image: elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - '9200:9200'

  kibana:
    image: kibana:8.10.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:8.10.1
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./nginx/logs:/var/log/nginx # Nginx 로그 디렉토리 공유
    ports:
      - '5044:5044'
    depends_on:
      - elasticsearch
